export enum ApiPaths {
  //login and register endpoint
  LoginApiEndpoint = '/EmployeeAuths/login',
  RegisterApiEndpoint = '/EmployeeAuths/register',

  ImageUploadEndpoint = '/Images',
  NotificationEndpoint = '/Notifications',
  MessageEndpoint = '/Messages',

  //Some Endpoints with get,post,put and delete method
  EmployeeEndpoint = '/Employees',
  PatientEndpoint = '/Patients',
  AdmissionEndpoint = '/Admissions',
  AdmissionTypeEndpoint = '/AdmissionTypes',
  PharmacyEndpoint = '/Pharmacy',
  MedicationEndpoint = '/Medications',
  MedicineCategoryEndpoint = '/MedicineCategories',
  MedSupplierEndpoint = '/MedSuppliers',
  PharmacyMedStockEndpoint = '/PharmacyMedStocks',
  PharmacySaleEndpoint = '/PharmacySales',
  PrescriptionEndpoint = '/Prescriptions',
  PharmacyExpenseCategoryEndpoint = '/PharmacyExpenseCatagories',
  PharmacyExpenseEndpoint = '/PharmacyExpenses',
  InventorySupplierEndpoint = '/InventorySupplies',
  InventoryEndpoint = '/Inventories',
  ExpenseEndpoint = '/Expenses',
  ExpenseCategoryEndpoint = '/ExpenseCatagories',
  RevenueEndpoint = '/Revenues',
  RevenueCategoryEndpoint = '/RevenueCategories',
  LabRequestEndpoint = '/LabRequests',
  LabTestCategoryEndpoint = '/LaboratoryTestCategories',
  LabTestResultEndpoint = '/LabTestResults',
  EditLabTestResultEndpoint = '/LabTestResults/edit',
  LabTestTypeEndpoint = '/LaboratoryTestTypes',
  MedicalHistoryDrugEndpoint = '/MedicalHistoryDrugs',
  MedicalHistoryEndpoint = '/MedicalHistories',
  PatientScheduleEndpoint = '/PatientSchedules',
  ScheduleStatusEndpoint = '/ScheduleStatus',
  AppointmentDurationEndpoint = '/AppointmentDurations',
  EmployeeSalaryEndpoint = '/EmployeeSalaries',
  PayrollReportEndpoint = '/PayrollReports',
  MedicalInterviewSocratesEndpoint = '/MedicalInterViewSocrates',
  BillLabEndpoint = '/BillLabs',
  BillSchedulesEndpoint = '/BillSchedules',
  ServiceChargeEndpoint = '/ServiceCharges',
  CaseEndpoint = '/Cases',
  OperationEndpoint = '/Operations',
  MedicineStockHospitalEndpoint = '/MedicineStockHospitals',
  NoticeEndpoint = '/Notices',
  MedicalHistoryFamilyEndpoint = '/MedicalHistoryFamilies',
  MedicalInterviewAllergyEndpoint = '/MedicalInterviewAllergies',
  MedicalCertificateEndpoint = '/MedicalCertificates',
  AllergyEndpoint = '/Allergies',

  //Some Endpoints with get,post,put and delete method
  EducationLevelEndpoint = '/EducationLevel',
  SpecializationEndPoint = '/Specializations',
  DesignationEndpoint = '/Designations',
  EmployeeRoleEndpoint = '/EmployeeRoles',
  MedicalDepartmentEndpoint = '/MedicalDepartments',
  BedAllotmentEndpoint = '/BedAllotments',
  BuildingEndpoint = '/Buildings',
  BedTypeEndpoint = '/BedTypes',
  AvailableEndpoint = '/Availables',
  RoomEndpoint = '/Rooms',
  WardEndpoint = '/Wards',
  WardTypeEndpoint = '/WardTypes',
  BedEndpoint = '/Beds',
  VaccineEndpoint = '/Vaccines',
  ScheduleEndpoint = '/Schedules',
  WeekDayEndpoint = '/WeekDays',
  PreExamCheckupEndpoint = '/PreExamCheckups',
  PaymentOptionEndpoint = '/PaymentOptions',
  PermissionEndpoint = '/Permissions',
  SpecializationEndpoint = '/Specializations',
  ResponsiblePersonEndpoint = '/ResponsiblePersons',
  AllowanceDeductionEndpoint = '/AllowanceDeductions',
  AllowanceDeductionTypeEndpoint = '/AllowanceDeductionTypes',
  TaxRuleEndpoint = '/TaxRules',

  BirthEndpoint = '/Births',
  DeathEndpoint = '/Deaths',
  DonorEndpoint = '/Donors',
  HolidayEndpoint = '/Holidays',
  OvertimeEndpoint = '/Overtimes',
  RecommendationEndpoint = '/Recommendations',

  //Some Endpoints with only get method
  LanguageEndpoint = '/Languages',
  MaritalStatuseEndpoint = '/MaritalStatuses',
  CitieEndpoint = '/Cities',
  CountryEndpoint = '/Countries',
  GenderEndpoint = '/Genders',
  RelationshipEndpoint = '/Relationships',
  BloodGroupEndpoint = '/BloodGroups',
  BloodGroupStatusEndpoint = '/BloodGroupStatus',
  EyewearPrescriptionEndpoint = '/EyewearPrescription'
}
